bitbucket.workspace=omnicell
bitbucket.username=savitha.satyanarayana@omnicell.com
bitbucket.app_password=ATATT3xFfGF00tQtBk2aNPyhLaSzCB7fBtS6cltlTwyVS8wu3damM181WA-kx3uYBFMB4-9iN7GVLGiTDRzOfx-U6ehzb8gjhcYWa2R3KFYJCIfMKLsagZJaThQHv1LykDIdzqKemf4qyiHa2pu1-mTMwVI4yR3kvJmJVT9-RF8F7ibl75-XCsk=BBAF2BBF
release.branch=release/2026-3-2
repos=ng-platform-ui,notifications
