bitbucket.workspace=test
bitbucket.username=savita.test@omnicell.com
bitbucket.app_password=atest-kx3uYBFMB4-9iN7GVLGiTDRzOfx-U6ehzb8gjhcYWa2R3KFYJCIfMKLsagZJaThQHv1LykDIdzqKemf4qyiHa2pu1-mTMwVI4yR3kvJmJVT9-RF8F7ibl75-XCsk=BBAF2BBF
release.branch=release/2026-3-2
repos=ng-platform-ui,notifications


openAI= sk-proj-teerer3ddddd-

jira.domain=https://omnidata.atlassian.net
# Jira email/username
jira.userid=savita.test@omnicell.com
# Jira API token
jira.api_token=2322222=06AD2D97
